const mockData = [
  {
    subreddit: "mildlyinfuriating",
    subredditNamePrefixed: "r/mildlyinfuriating",
    author: "henryhendrixx",
    title:
      "Someone has been cutting our Christmas lights. Today we caught the culprit!",
    selfText:
      "The first day we thought it was Jehovas Witnesses (the only people to approach the house that day). The second day we thought it was kids just outside of the cameras view. The third day we found out who it was. I had no idea rabbits could produce such clean cuts!",
    numComments: 777,
    score: 15878,
    media:
      "https://th-thumbnailer.cdn-si-edu.com/bgmkh2ypz03IkiRR50I-UMaqUQc=/1000x750/filters:no_upscale():focal(1061x707:1062x708)/https://tf-cmsv2-smithsonianmag-media.s3.amazonaws.com/filer_public/55/95/55958815-3a8a-4032-ac7a-ff8c8ec8898a/gettyimages-1067956982.jpg",
    date: "4 hours ago",
    isImage: true,
    isVideo: false,
    hasMedia: true,
  },
  {
    subreddit: "2meirl4meirl",
    subredditNamePrefixed: "r/2meirl4meirl",
    author: "opliku",
    title: "2meirl4meirl",
    selfText: "",
    numComments: 471,
    score: 11886,
    media: "https://i.redd.it/qq6wnpd8v25c1.png",
    date: "3 hours ago",
    isImage: true,
    isVideo: false,
    hasMedia: true,
  },
  {
    subreddit: "facepalm",
    subredditNamePrefixed: "r/facepalm",
    author: "Bizzyguy",
    title: "This can't end well",
    selfText: "",
    numComments: 1202,
    score: 14679,
    media: "https://i.redd.it/rjfy6fn1i25c1.jpeg",
    date: "18 hours ago",
    isImage: true,
    isVideo: false,
    hasMedia: true,
  },
  {
    subreddit: "nextfuckinglevel",
    subredditNamePrefixed: "r/nextfuckinglevel",
    author: "",
    title:
      "Fashioning ninja throwing stars from obsidian with the help of simple tools.",
    selfText: "",
    numComments: 315,
    score: 12599,
    media: "https://v.redd.it/u7zkk6d6t25c1/DASH_720.mp4?source=fallback",
    date: "1 hour ago",
    isImage: false,
    isVideo: true,
    hasMedia: true,
  },
  {
    subreddit: "todayilearned",
    subredditNamePrefixed: "r/todayilearned",
    author: "",
    title:
      "TIL Van Gogh's sister in law was behind Van Gogh’s posthumous success and fame, She dedicated her life to spreading his art and legacy after his death, She preserved and published his letters, organized and exhibited his paintings, wrote and translated articles and books about him",
    selfText: "",
    numComments: 220,
    score: 15715,
    media: "https://wikipedia.org/wiki/Johanna_van_Gogh-Bonger",
    date: "4 hours ago",
    isImage: false,
    isVideo: false,
    hasMedia: null,
  },
];

export default mockData;
